# Generated by Django 3.2.8 on 2021-10-20 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0005_remove_flowelementscontainer_goal'),
        ('kipco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntensiveProcess',
            fields=[
                ('flowelementscontainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bpmn.flowelementscontainer')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kipco.processgoal')),
            ],
            bases=('bpmn.flowelementscontainer',),
        ),
    ]
