# Generated by Django 3.2.8 on 2021-10-20 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kipco', '0003_intensiveprocess_storeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intensiveprocess',
            old_name='storeid',
            new_name='storid',
        ),
    ]
