# Generated by Django 3.2.8 on 2021-10-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipco', '0004_rename_storeid_intensiveprocess_storid'),
    ]

    operations = [
        migrations.AddField(
            model_name='processgoal',
            name='storid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='processgoal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
