# Generated by Django 3.2.8 on 2021-10-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipco', '0005_auto_20211021_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intensiveprocess',
            name='storid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processgoal',
            name='storid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
