# Generated by Django 3.2.8 on 2021-10-08 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlowElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlowElementsContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FlowNode',
            fields=[
                ('flowelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bpmn.flowelement')),
            ],
            bases=('bpmn.flowelement',),
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('flowelementscontainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bpmn.flowelementscontainer')),
            ],
            bases=('bpmn.flowelementscontainer',),
        ),
        migrations.CreateModel(
            name='LaneSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmn.flowelementscontainer')),
            ],
        ),
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmn.laneset')),
            ],
        ),
        migrations.AddField(
            model_name='flowelement',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmn.flowelementscontainer'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('flownode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bpmn.flownode')),
            ],
            bases=('bpmn.flownode',),
        ),
        migrations.CreateModel(
            name='SequenceFlow',
            fields=[
                ('flowelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bpmn.flowelement')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='bpmn.flownode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='bpmn.flownode')),
            ],
            bases=('bpmn.flowelement',),
        ),
        migrations.CreateModel(
            name='SubProcess',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bpmn.activity')),
            ],
            bases=('bpmn.activity',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bpmn.activity')),
            ],
            bases=('bpmn.activity',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('flownode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bpmn.flownode')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmn.eventtype')),
            ],
            bases=('bpmn.flownode',),
        ),
    ]
