# Generated by Django 3.2.8 on 2021-10-20 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kipco', '0001_initial'),
        ('bpmn', '0003_bag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowelementscontainer',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kipco.processgoal'),
        ),
    ]
