# Generated by Django 3.2.8 on 2021-10-20 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0004_alter_flowelementscontainer_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowelementscontainer',
            name='goal',
        ),
    ]
